# Generated by Django 4.0.2 on 2022-02-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_quesmodel_dif'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='dis',
            field=models.FloatField(null=True),
        ),
    ]
