# Generated by Django 4.0.2 on 2022-02-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_quesmodel_dis'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='questionid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
