# Generated by Django 4.0.2 on 2022-03-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_basechemquesmodel_baseengquesmodel_basemathquesmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basechemquesmodel',
            old_name='questionid',
            new_name='qid',
        ),
        migrations.RenameField(
            model_name='baseengquesmodel',
            old_name='questionid',
            new_name='qid',
        ),
        migrations.RenameField(
            model_name='basemathquesmodel',
            old_name='questionid',
            new_name='qid',
        ),
        migrations.RenameField(
            model_name='basephyquesmodel',
            old_name='questionid',
            new_name='qid',
        ),
        migrations.RenameField(
            model_name='chemquesmodel',
            old_name='questionid',
            new_name='qid',
        ),
        migrations.RenameField(
            model_name='engquesmodel',
            old_name='questionid',
            new_name='qid',
        ),
        migrations.RenameField(
            model_name='mathquesmodel',
            old_name='questionid',
            new_name='qid',
        ),
        migrations.RenameField(
            model_name='phyquesmodel',
            old_name='questionid',
            new_name='qid',
        ),
    ]
