# Generated by Django 4.0.1 on 2022-03-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_rename_questionid_basechemquesmodel_qid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERID', models.CharField(max_length=50)),
                ('Physics', models.FloatField(null=True)),
                ('Chemistry', models.FloatField(null=True)),
                ('Maths', models.FloatField(null=True)),
                ('English', models.FloatField(null=True)),
            ],
        ),
    ]
