# Generated by Django 4.0.1 on 2022-03-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='Total',
            field=models.FloatField(null=True),
        ),
    ]
